### ISSUE TITLE
update `{epidemics}` code and package version in `renv.lock`

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/tutorials#100]
> I suspect that different episodes were written with different versions of epidemics. This is my best guess to explain the error messages we currently have in the "Simulating transmission" episode: https://epiverse-trace.github.io/tutorials/simulating-transmission.html#introduction

_Originally posted by @Bisaloo in https://github.com/epiverse-trace/tutorials/issues/93#issuecomment-1864798730_

**Comment by avallecam** [comment]
@amanda-minter can you inspect this and do this fixing?

**Comment by amanda-minter** [comment]
the tutorials on the [update-late-tasks ]( https://github.com/epiverse-trace/tutorials/tree/update-late-tasks ) branch contain the updated functions for current version of {epidemics}, but with the update from main of removing {pak} from the setup, the episodes are now giving errors 

is this a `renv.lock` issue?

**Comment by avallecam** [comment]
I will try to run your recent updates locally. then, I'll inspect how the `renv.lock` is updated. I'll report back.

**Comment by Bisaloo** [comment]
This is solved by the following patch on top of `update-late-tasks`:

```
From 1e3d74c750353ecf27ee11740f07a59dc8b02ed1 Mon Sep 17 00:00:00 2001
From: Hugo Gruson <Bisaloo@users.noreply.github.com>
Date: Thu, 21 Dec 2023 13:31:22 +0100
Subject: [PATCH 1/2] Update lockfile to the latest epidemics version

---
 renv/profiles/lesson-requirements/renv.lock | 11 +++++------
 1 file changed, 5 insertions(+), 6 deletions(-)

diff --git a/renv/profiles/lesson-requirements/renv.lock b/renv/profiles/lesson-requirements/renv.lock
index b87ec9c..8602455 100644
--- a/renv/profiles/lesson-requirements/renv.lock
+++ b/renv/profiles/lesson-requirements/renv.lock
@@ -567,24 +567,23 @@
       "Source": "GitHub",
       "RemoteType": "github",
       "RemoteHost": "api.github.com",
-      "RemoteRepo": "epidemics",
       "RemoteUsername": "epiverse-trace",
-      "RemotePkgRef": "epiverse-trace/epidemics",
-      "RemoteRef": "HEAD",
-      "RemoteSha": "6004c3a7e50be7b127070c4e96a011630307df17",
+      "RemoteRepo": "epidemics",
+      "RemoteRef": "main",
+      "RemoteSha": "5f6825d7ee9fbd162b26db95bc2f3e0d3054f452",
       "Requirements": [
         "BH",
         "Rcpp",
         "RcppEigen",
         "checkmate",
+        "cli",
         "data.table",
         "deSolve",
         "glue",
-        "jsonlite",
         "stats",
         "utils"
       ],
-      "Hash": "96a7b1457b8a5d89f146d0abf3de7eff"
+      "Hash": "5abca47c2b33eb1a73a412a045823a8f"
     },
     "evaluate": {
       "Package": "evaluate",
-- 
2.43.0
```

@amanda-minter, should I push it directly to you branch or do you want to add the patch yourself?

**Comment by Bisaloo** [comment]
In a nutshell, and for some context behind the removal of `pak::pak()` in #93:

We want to be able to associate the training materials to a specific versions of epidemics. If only to ensure that the lesson is not completely broken if we are not able to address epidemics latest breaking changes right off the bat.

This is what renv is doing. We want this ability to say "always install this exact version of epidemics" and create the website with it.

This has two consequences:

- we should not overwrite renv instructions by using `pak::pak()` and installing the latest version of epidemics, which is one week may again no longer be perfectly aligned with the training materials. Or at least, we want a warning when this happens so we know the materials need to be updated, which is what automated pull requests like #93 are doing.
- if we update the materials to work with a different version of epidemics, as #85 is doing, we need to update `renv.lock` at the same time, to inform the lesson building infrastructure which specific version of epidemics we are using to build this lesson.

**Comment by avallecam** [comment]
Thank you, Hugo, for sharing the patch. 

I caught this update for `{epidemics}` update running `sandpaper::update_cache()` (with the same `remotesha` but different `Hash`) do you recommend doing this edit manually, instead?

Then, I was still getting the current errors, but after adding the namespace before `model_default_cpp()` they were solved! so the additional edit to do would be to use the notation `epidemics::model_default_cpp()` each time `model_default_cpp()` is called.

**Comment by Bisaloo** [comment]
> I caught this update for {epidemics} running sandpaper::update_cache() (with the same remotesha but a different Hash) do you recommend doing this edit manually, instead?

No preference. Both mechanisms are equivalent.

> Then, I was still getting the current errors, but after adding the namespace before model_default_cpp() they were solved! so the additional edit to do would be to use the notation epidemics::model_default_cpp() each time model_default_cpp() is called.

I had the same issue but realized it's a rendering caching issue since it doesn't make sense that we would need namespacing if we already loaded the package. If you delete `site/` and re-render, it will work without namespacing.

Explanation: sandpaper has a mechanism to automatically detect which files have changed and need to be re-rendered. When we update `renv.lock` only, the source files don't change and sandpaper assumes it can use a previously rendered version. When you added the namespace, you edited the source file, which triggered a fresh render and looked like it had solved the issue.

**Comment by avallecam** [comment]
> Explanation: sandpaper has a mechanism to automatically detect which files have changed and need to be re-rendered. When we update `renv.lock` only, the source files don't change and sandpaper assumes it can use a previously rendered version. When you added the namespace, you edited the source file, which triggered a fresh render and looked like it had solved the issue.

ohhhh, that makes a lot of sense! I just saw that the whole document was fixed with only that edit! probably we can also use `sandpaper::build_lesson(rebuild = TRUE)` each time we expect to get a rebuild without cache?

**Comment by avallecam** [comment]
Thank you both! this is now solved, and a lot of lessons learned.

I'll add the package installation details in the setup #99
